theme = "default"
baseurl = "http://example.com/"
languageCode = "en-us"
title = "Example"
MetaDataFormat = "toml"
pluralizeListTitles = false
Paginate = "10"
PageSize = "10"

[taxonomies]
  tag = "tags"
  category = "categories"
  status = "status"
